// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDlTE7792IfJBZJNu2NeBCR39W2h68PcI',
    appId: '1:445900814761:android:7c2a42e51a81c7bebf6cb8',
    messagingSenderId: '445900814761',
    projectId: 'water-level-7ea9e',
    databaseURL: 'https://water-level-7ea9e-default-rtdb.firebaseio.com',
    storageBucket: 'water-level-7ea9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDdYBu5EYy1yBjLH-eYiEThdIpP8pfmMw',
    appId: '1:445900814761:ios:0298ac627803788abf6cb8',
    messagingSenderId: '445900814761',
    projectId: 'water-level-7ea9e',
    databaseURL: 'https://water-level-7ea9e-default-rtdb.firebaseio.com',
    storageBucket: 'water-level-7ea9e.appspot.com',
    iosClientId: '445900814761-sl4tt7tdirbo6lh1f6bk973gjlqbic0k.apps.googleusercontent.com',
    iosBundleId: 'com.example.watwe',
  );
}
